export const strings = {
  en: {
    intro: {
      skip: 'Skip',
      next: 'Next',
      getStarted: 'Get Started',
      welcome: 'Welcome to SharePost',
      subtitle: 'Create beautiful posts with photos, themes, and more',
    },
    common: {
      continue: 'Continue',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      share: 'Share',
    },
    features: {
      addPhotos: 'Add Your Photos',
      addPhotosDesc:
        'Upload and share your favorite photos with beautiful backgrounds',
      personalize: 'Personalize Your Profile',
      personalizeDesc:
        'Add your name and social media links to connect with others',
      celebrate: 'Celebrate Special Days',
      celebrateDesc:
        'Choose from themes like Republic Day, festivals, and inspirational thoughts',
      share: 'Share & Inspire',
      shareDesc:
        'Create beautiful posts and share them with your friends and family',
    },
    language: {
      title: 'Select Language',
      subtitle: 'Choose your preferred language',
      selectLanguage: 'Select Language',
      currentLanguage: 'Current Language',
      continue: 'Continue',
    },
    home: {
      title: 'Home',
      welcome: 'Welcome',
      welcomeUser: 'Welcome User',
      goodMorning: 'Good Morning',
      goodAfternoon: 'Good Afternoon',
      goodEvening: 'Good Evening',
      searchPlaceholder: 'Search...',
      selectCategory: 'Select Category',
      createPost: 'Create Post',
      myPosts: 'My Posts',
      noPosts: 'No posts yet',
      createFirstPost: 'Create your first post to get started',
      categories: {
        all: 'All',
        newYear: 'New Year',
        goodMorning: 'Good Morning',
        goodNight: 'Good Night',
        suvichar: 'Suvichar',
      },
      download: 'Download',
      edit: 'Edit',
      more: 'More',
      customize: 'Customize',
    },
    create: {
      title: 'Create',
      selectBackground: 'Select Background',
      imageBackground: 'Image Background',
      textBackground: 'Text Background',
      chooseImage: 'Choose Image',
      takePhoto: 'Take Photo',
      chooseFromGallery: 'Choose from Gallery',
      enterText: 'Enter Text',
      backgroundColor: 'Background Color',
      fontColor: 'Font Color',
      fontSize: 'Font Size',
      small: 'Small',
      medium: 'Medium',
      large: 'Large',
      download: 'Download',
      share: 'Share',
    },
    settings: {
      title: 'Settings',
      profile: 'Profile',
      language: 'Language',
      theme: 'Theme',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      about: 'About',
      logout: 'Logout',
      version: 'Version',
    },
    profile: {
      title: 'Profile',
      editProfile: 'Edit Profile',
      fullName: 'Full Name',
      phoneNumber: 'Phone Number',
      bio: 'Bio / Description',
      facebook: 'Facebook',
      instagram: 'Instagram',
      twitter: 'Twitter',
      save: 'Save',
      cancel: 'Cancel',
      faq: 'FAQ',
      terms: 'Terms and Conditions',
      privacy: 'Privacy Policy',
      subscriptions: 'Subscriptions',
      shareApp: 'Share App',
      deleteAccount: 'Delete Account',
      deleteAccountWarning: 'This action cannot be undone',
      nameRequired: 'Name is required',
      phoneInvalid: 'Invalid phone number',
      urlInvalid: 'Invalid URL',
      saveSuccess: 'Profile updated successfully',
      saveError: 'Failed to update profile',
    },
    downloadShare: {
      title: 'Unlock Premium Features',
      description:
        'To download/share posts, please choose one of the following options:',
      viewAds: 'View Ads',
      viewAdsDescription: 'Watch a short ad to unlock this feature',
      purchaseSubscription: 'Purchase Subscription',
      purchaseDescription: 'Get unlimited downloads and shares',
      download: 'Download',
      share: 'Share',
      loadingAd: 'Loading Ad...',
    },
    subscription: {
      title: 'Choose Your Plan',
      monthly: 'Monthly',
      yearly: 'Yearly',
      month: 'Month',
      year: 'Year',
      monthlyDescription: 'Access to premium features for one month',
      yearlyDescription:
        'Access to premium features for one year at a discounted rate',
      benefitsTitle: 'Premium Features',
      benefit1: 'Unlimited post creation',
      benefit2: 'Access to all premium themes and backgrounds',
      benefit3: 'High-quality image downloads',
      benefit4: 'Priority customer support',
      benefit5: 'Ad-free experience',
      subscribeNow: 'Subscribe Now',
    },
    auth: {
      login: 'Login',
      signUp: 'Sign Up',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      forgotPassword: 'Forgot Password?',
      continueAsGuest: 'Continue as Guest',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      createAccount: 'Create Account',
      otpVerification: 'OTP Verification',
      otpSent: 'OTP sent to your email',
      enterOTP: 'Enter OTP',
      verify: 'Verify',
      resendOTP: 'Resend OTP',
      personalDetails: 'Personal Details',
      uploadPhoto: 'Upload Photo',
      takePhoto: 'Take Photo',
      chooseFromGallery: 'Choose from Gallery',
      continue: 'Continue',
      emailRequired: 'Email is required',
      emailInvalid: 'Invalid email format',
      passwordRequired: 'Password is required',
      passwordMinLength: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      otpRequired: 'OTP is required',
      otpInvalid: 'Invalid OTP',
      nameRequired: 'Name is required',
      loginSuccess: 'Login successful',
      loginError: 'Login failed',
      signUpSuccess: 'Account created successfully',
      signUpError: 'Sign up failed',
      otpSuccess: 'OTP verified successfully',
      otpError: 'OTP verification failed',
      resetPasswordDescription:
        "Enter your email address and we'll send you a link to reset your password.",
      sendResetLink: 'Send Reset Link',
      resetPasswordEmailSent: 'Email Sent!',
      resetPasswordCheckEmail:
        'Please check your email for password reset instructions. The link will expire in 1 hour.',
      resetPasswordError: 'Failed to send reset email',
      rememberPassword: 'Remember your password?',
      backToLogin: 'Back to Login',
    },
  },
  hi: {
    intro: {
      skip: 'छोड़ें',
      next: 'अगला',
      getStarted: 'शुरू करें',
      welcome: 'SharePost में आपका स्वागत है',
      subtitle: 'फ़ोटो, थीम और अधिक के साथ सुंदर पोस्ट बनाएं',
    },
    common: {
      continue: 'जारी रखें',
      cancel: 'रद्द करें',
      save: 'सहेजें',
      delete: 'हटाएं',
      edit: 'संपादित करें',
      share: 'साझा करें',
    },
    features: {
      addPhotos: 'अपनी फ़ोटो जोड़ें',
      addPhotosDesc:
        'सुंदर पृष्ठभूमि के साथ अपनी पसंदीदा फ़ोटो अपलोड और साझा करें',
      personalize: 'अपना प्रोफ़ाइल व्यक्तिगत बनाएं',
      personalizeDesc:
        'दूसरों के साथ जुड़ने के लिए अपना नाम और सोशल मीडिया लिंक जोड़ें',
      celebrate: 'विशेष दिन मनाएं',
      celebrateDesc:
        'गणतंत्र दिवस, त्योहार और प्रेरणादायक विचार जैसी थीम चुनें',
      share: 'साझा करें और प्रेरित करें',
      shareDesc:
        'सुंदर पोस्ट बनाएं और उन्हें अपने दोस्तों और परिवार के साथ साझा करें',
    },
    language: {
      title: 'भाषा चुनें',
      subtitle: 'अपनी पसंदीदा भाषा चुनें',
      selectLanguage: 'भाषा चुनें',
      currentLanguage: 'वर्तमान भाषा',
      continue: 'जारी रखें',
    },
    home: {
      title: 'होम',
      welcome: 'स्वागत है',
      welcomeUser: 'स्वागत है यूजर',
      goodMorning: 'सुप्रभात',
      goodAfternoon: 'नमस्कार',
      goodEvening: 'शुभ संध्या',
      searchPlaceholder: 'खोजें...',
      selectCategory: 'श्रेणी चुनें',
      createPost: 'पोस्ट बनाएं',
      myPosts: 'मेरी पोस्ट',
      noPosts: 'अभी तक कोई पोस्ट नहीं',
      createFirstPost: 'शुरू करने के लिए अपनी पहली पोस्ट बनाएं',
      categories: {
        all: 'सभी',
        newYear: 'नव वर्ष',
        goodMorning: 'सुप्रभात',
        goodNight: 'शुभ रात्रि',
        suvichar: 'सुविचार',
      },
      download: 'डाउनलोड',
      edit: 'संपादित करें',
      more: 'अधिक',
      customize: 'अनुकूलित करें',
    },
    create: {
      title: 'बनाएं',
      selectBackground: 'पृष्ठभूमि चुनें',
      imageBackground: 'छवि पृष्ठभूमि',
      textBackground: 'टेक्स्ट पृष्ठभूमि',
      chooseImage: 'छवि चुनें',
      takePhoto: 'फोटो लें',
      chooseFromGallery: 'गैलरी से चुनें',
      enterText: 'टेक्स्ट दर्ज करें',
      backgroundColor: 'पृष्ठभूमि रंग',
      fontColor: 'फ़ॉन्ट रंग',
      fontSize: 'फ़ॉन्ट आकार',
      small: 'छोटा',
      medium: 'मध्यम',
      large: 'बड़ा',
      download: 'डाउनलोड',
      share: 'साझा करें',
    },
    settings: {
      title: 'सेटिंग्स',
      profile: 'प्रोफ़ाइल',
      language: 'भाषा',
      theme: 'थीम',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      about: 'के बारे में',
      logout: 'लॉगआउट',
      version: 'संस्करण',
    },
    profile: {
      title: 'प्रोफ़ाइल',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      fullName: 'पूरा नाम',
      phoneNumber: 'फ़ोन नंबर',
      bio: 'बायो / विवरण',
      facebook: 'फेसबुक',
      instagram: 'इंस्टाग्राम',
      twitter: 'ट्विटर',
      save: 'सहेजें',
      cancel: 'रद्द करें',
      faq: 'FAQ',
      terms: 'नियम और शर्तें',
      privacy: 'गोपनीयता नीति',
      subscriptions: 'सदस्यता',
      shareApp: 'ऐप साझा करें',
      deleteAccount: 'खाता हटाएं',
      deleteAccountWarning: 'यह कार्रवाई पूर्ववत नहीं की जा सकती',
      nameRequired: 'नाम आवश्यक है',
      phoneInvalid: 'अमान्य फ़ोन नंबर',
      urlInvalid: 'अमान्य URL',
      saveSuccess: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',
      saveError: 'प्रोफ़ाइल अपडेट करने में विफल',
    },
    auth: {
      login: 'लॉगिन',
      signUp: 'साइन अप',
      email: 'ईमेल',
      password: 'पासवर्ड',
      confirmPassword: 'पासवर्ड की पुष्टि करें',
      forgotPassword: 'पासवर्ड भूल गए?',
      continueAsGuest: 'अतिथि के रूप में जारी रखें',
      dontHaveAccount: 'खाता नहीं है?',
      alreadyHaveAccount: 'पहले से खाता है?',
      createAccount: 'खाता बनाएं',
      otpVerification: 'OTP सत्यापन',
      otpSent: 'OTP आपके ईमेल पर भेजा गया',
      enterOTP: 'OTP दर्ज करें',
      verify: 'सत्यापित करें',
      resendOTP: 'OTP पुनः भेजें',
      personalDetails: 'व्यक्तिगत विवरण',
      uploadPhoto: 'फोटो अपलोड करें',
      takePhoto: 'फोटो लें',
      chooseFromGallery: 'गैलरी से चुनें',
      continue: 'जारी रखें',
      emailRequired: 'ईमेल आवश्यक है',
      emailInvalid: 'अमान्य ईमेल प्रारूप',
      passwordRequired: 'पासवर्ड आवश्यक है',
      passwordMinLength: 'पासवर्ड कम से कम 6 वर्ण का होना चाहिए',
      passwordMismatch: 'पासवर्ड मेल नहीं खाते',
      otpRequired: 'OTP आवश्यक है',
      otpInvalid: 'अमान्य OTP',
      nameRequired: 'नाम आवश्यक है',
      loginSuccess: 'लॉगिन सफल',
      loginError: 'लॉगिन विफल',
      signUpSuccess: 'खाता सफलतापूर्वक बनाया गया',
      signUpError: 'साइन अप विफल',
      otpSuccess: 'OTP सफलतापूर्वक सत्यापित',
      otpError: 'OTP सत्यापन विफल',
      resetPasswordDescription:
        'अपना ईमेल पता दर्ज करें और हम आपको पासवर्ड रीसेट करने के लिए एक लिंक भेजेंगे।',
      sendResetLink: 'रीसेट लिंक भेजें',
      resetPasswordEmailSent: 'ईमेल भेजा गया!',
      resetPasswordCheckEmail:
        'कृपया पासवर्ड रीसेट निर्देशों के लिए अपना ईमेल जांचें। लिंक 1 घंटे में समाप्त हो जाएगा।',
      resetPasswordError: 'रीसेट ईमेल भेजने में विफल',
      rememberPassword: 'अपना पासवर्ड याद है?',
      backToLogin: 'लॉगिन पर वापस जाएं',
    },
  },
  gu: {
    intro: {
      skip: 'છોડો',
      next: 'આગળ',
      getStarted: 'શરૂ કરો',
      welcome: 'SharePost માં આપનું સ્વાગત છે',
      subtitle: 'ફોટા, થીમ્સ અને વધુ સાથે સુંદર પોસ્ટ્સ બનાવો',
    },
    common: {
      continue: 'ચાલુ રાખો',
      cancel: 'રદ કરો',
      save: 'સાચવો',
      delete: 'કાઢી નાખો',
      edit: 'સંપાદિત કરો',
      share: 'શેર કરો',
    },
    features: {
      addPhotos: 'તમારા ફોટા ઉમેરો',
      addPhotosDesc: 'સુંદર પૃષ્ઠભૂમિ સાથે તમારા પ્રિય ફોટા અપલોડ અને શેર કરો',
      personalize: 'તમારી પ્રોફાઇલ વ્યક્તિગત બનાવો',
      personalizeDesc:
        'બીજાઓ સાથે જોડાવા માટે તમારું નામ અને સોશિયલ મીડિયા લિંક્સ ઉમેરો',
      celebrate: 'ખાસ દિવસો ઉજવો',
      celebrateDesc:
        'ગણતંત્ર દિવસ, તહેવારો અને પ્રેરણાદાયક વિચારો જેવી થીમ્સ પસંદ કરો',
      share: 'શેર કરો અને પ્રેરણા આપો',
      shareDesc:
        'સુંદર પોસ્ટ્સ બનાવો અને તેમને તમારા મિત્રો અને પરિવાર સાથે શેર કરો',
    },
    language: {
      title: 'ભાષા પસંદ કરો',
      subtitle: 'તમારી પ્રિય ભાષા પસંદ કરો',
      selectLanguage: 'ભાષા પસંદ કરો',
      currentLanguage: 'વર્તમાન ભાષા',
      continue: 'ચાલુ રાખો',
    },
    home: {
      title: 'હોમ',
      welcome: 'સ્વાગત છે',
      welcomeUser: 'સ્વાગત છે યુઝર',
      goodMorning: 'સુપ્રભાત',
      goodAfternoon: 'નમસ્તે',
      goodEvening: 'શુભ સાંજ',
      searchPlaceholder: 'શોધો...',
      selectCategory: 'શ્રેણી પસંદ કરો',
      createPost: 'પોસ્ટ બનાવો',
      myPosts: 'મારી પોસ્ટ્સ',
      noPosts: 'હજુ સુધી કોઈ પોસ્ટ નથી',
      createFirstPost: 'શરૂ કરવા માટે તમારી પહેલી પોસ્ટ બનાવો',
      categories: {
        all: 'બધા',
        newYear: 'નવું વર્ષ',
        goodMorning: 'સુપ્રભાત',
        goodNight: 'શુભ રાત્રી',
        suvichar: 'સુવિચાર',
      },
      download: 'ડાઉનલોડ',
      edit: 'સંપાદિત કરો',
      more: 'વધુ',
      customize: 'કસ્ટમાઇઝ કરો',
    },
    settings: {
      title: 'સેટિંગ્સ',
      profile: 'પ્રોફાઇલ',
      language: 'ભાષા',
      theme: 'થીમ',
      darkMode: 'ડાર્ક મોડ',
      lightMode: 'લાઇટ મોડ',
      about: 'વિશે',
      logout: 'લોગઆઉટ',
      version: 'વર્ઝન',
    },
    profile: {
      title: 'પ્રોફાઇલ',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      fullName: 'પૂરું નામ',
      phoneNumber: 'ફોન નંબર',
      bio: 'બાયો / વર્ણન',
      facebook: 'ફેસબુક',
      instagram: 'ઇન્સ્ટાગ્રામ',
      twitter: 'ટ્વિટર',
      save: 'સાચવો',
      cancel: 'રદ કરો',
      faq: 'FAQ',
      terms: 'નિયમો અને શરતો',
      privacy: 'ગોપનીયતા નીતિ',
      subscriptions: 'સબ્સ્ક્રિપ્શન',
      shareApp: 'એપ્લિકેશન શેર કરો',
      deleteAccount: 'એકાઉન્ટ કાઢી નાખો',
      deleteAccountWarning: 'આ ક્રિયા પૂર્વવત્ કરી શકાતી નથી',
      nameRequired: 'નામ જરૂરી છે',
      phoneInvalid: 'અમાન્ય ફોન નંબર',
      urlInvalid: 'અમાન્ય URL',
      saveSuccess: 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ',
      saveError: 'પ્રોફાઇલ અપડેટ કરવામાં નિષ્ફળ',
    },
    auth: {
      login: 'લોગિન',
      signUp: 'સાઇન અપ',
      email: 'ઇમેઇલ',
      password: 'પાસવર્ડ',
      confirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
      forgotPassword: 'પાસવર્ડ ભૂલી ગયા છો?',
      continueAsGuest: 'મહેમાન તરીકે ચાલુ રાખો',
      dontHaveAccount: 'ખાતું નથી?',
      alreadyHaveAccount: 'પહેલેથી ખાતું છે?',
      createAccount: 'ખાતું બનાવો',
      otpVerification: 'OTP ચકાસણી',
      otpSent: 'OTP તમારા ઇમેઇલ પર મોકલ્યો છે',
      enterOTP: 'OTP દાખલ કરો',
      verify: 'ચકાસો',
      resendOTP: 'OTP ફરીથી મોકલો',
      personalDetails: 'વ્યક્તિગત વિગતો',
      uploadPhoto: 'ફોટો અપલોડ કરો',
      takePhoto: 'ફોટો લો',
      chooseFromGallery: 'ગેલેરીમાંથી પસંદ કરો',
      continue: 'ચાલુ રાખો',
      emailRequired: 'ઇમેઇલ જરૂરી છે',
      emailInvalid: 'અમાન્ય ઇમેઇલ ફોર્મેટ',
      passwordRequired: 'પાસવર્ડ જરૂરી છે',
      passwordMinLength: 'પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરનો હોવો જોઈએ',
      passwordMismatch: 'પાસવર્ડ મેળ ખાતા નથી',
      otpRequired: 'OTP જરૂરી છે',
      otpInvalid: 'અમાન્ય OTP',
      nameRequired: 'નામ જરૂરી છે',
      loginSuccess: 'લોગિન સફળ',
      loginError: 'લોગિન નિષ્ફળ',
      signUpSuccess: 'ખાતું સફળતાપૂર્વક બનાવ્યું',
      signUpError: 'સાઇન અપ નિષ્ફળ',
      otpSuccess: 'OTP સફળતાપૂર્વક ચકાસાયું',
      otpError: 'OTP ચકાસણી નિષ્ફળ',
      resetPasswordDescription:
        'તમારું ઇમેઇલ સરનામું દાખલ કરો અને અમે તમને તમારો પાસવર્ડ રીસેટ કરવા માટે એક લિંક મોકલીશું.',
      sendResetLink: 'રીસેટ લિંક મોકલો',
      resetPasswordEmailSent: 'ઇમેઇલ મોકલ્યો!',
      resetPasswordCheckEmail:
        'કૃપા કરીને પાસવર્ડ રીસેટ સૂચનાઓ માટે તમારું ઇમેઇલ તપાસો. લિંક 1 કલાકમાં સમાપ્ત થશે.',
      resetPasswordError: 'રીસેટ ઇમેઇલ મોકલવામાં અસફળ',
      rememberPassword: 'તમારો પાસવર્ડ યાદ છે?',
      backToLogin: 'લૉગિન પર પાછા જાઓ',
    },
  },
  mr: {
    intro: {
      skip: 'वगळा',
      next: 'पुढे',
      getStarted: 'सुरू करा',
      welcome: 'SharePost मध्ये आपले स्वागत आहे',
      subtitle: 'फोटो, थीम आणि अधिक सह सुंदर पोस्ट तयार करा',
    },
    common: {
      continue: 'सुरू ठेवा',
      cancel: 'रद्द करा',
      save: 'जतन करा',
      delete: 'हटवा',
      edit: 'संपादन करा',
      share: 'शेअर करा',
    },
    features: {
      addPhotos: 'आपले फोटो जोडा',
      addPhotosDesc:
        'सुंदर पार्श्वभूमीसह आपले आवडते फोटो अपलोड करा आणि शेअर करा',
      personalize: 'आपली प्रोफाइल वैयक्तिक करा',
      personalizeDesc: 'इतरांशी जोडण्यासाठी आपले नाव आणि सोशल मीडिया लिंक जोडा',
      celebrate: 'विशेष दिवस साजरे करा',
      celebrateDesc:
        'प्रजासत्ताक दिन, सण आणि प्रेरणादायी विचार यासारख्या थीम निवडा',
      share: 'शेअर करा आणि प्रेरणा द्या',
      shareDesc:
        'सुंदर पोस्ट तयार करा आणि त्या आपल्या मित्रांसोबत आणि कुटुंबासोबत शेअर करा',
    },
    language: {
      title: 'भाषा निवडा',
      subtitle: 'आपली पसंतीची भाषा निवडा',
      selectLanguage: 'भाषा निवडा',
      currentLanguage: 'सध्याची भाषा',
      continue: 'सुरू ठेवा',
    },
    home: {
      title: 'होम',
      welcome: 'स्वागत आहे',
      welcomeUser: 'स्वागत आहे यूजर',
      goodMorning: 'सुप्रभात',
      goodAfternoon: 'नमस्कार',
      goodEvening: 'शुभ संध्याकाळ',
      searchPlaceholder: 'शोधा...',
      selectCategory: 'श्रेणी निवडा',
      createPost: 'पोस्ट तयार करा',
      myPosts: 'माझ्या पोस्ट',
      noPosts: 'अद्याप कोणतीही पोस्ट नाही',
      createFirstPost: 'सुरू करण्यासाठी आपली पहिली पोस्ट तयार करा',
      categories: {
        all: 'सर्व',
        newYear: 'नवीन वर्ष',
        goodMorning: 'सुप्रभात',
        goodNight: 'शुभ रात्री',
        suvichar: 'सुविचार',
      },
      download: 'डाउनलोड',
      edit: 'संपादन करा',
      more: 'अधिक',
      customize: 'सानुकूलित करा',
    },
    settings: {
      title: 'सेटिंग्ज',
      profile: 'प्रोफाइल',
      language: 'भाषा',
      theme: 'थीम',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      about: 'बद्दल',
      logout: 'लॉगआउट',
      version: 'आवृत्ती',
    },
    profile: {
      title: 'प्रोफाइल',
      editProfile: 'प्रोफाइल संपादन करा',
      fullName: 'पूर्ण नाव',
      phoneNumber: 'फोन नंबर',
      bio: 'बायो / वर्णन',
      facebook: 'फेसबुक',
      instagram: 'इंस्टाग्राम',
      twitter: 'ट्विटर',
      save: 'जतन करा',
      cancel: 'रद्द करा',
      faq: 'FAQ',
      terms: 'अटी आणि नियम',
      privacy: 'गोपनीयता धोरण',
      subscriptions: 'सदस्यता',
      shareApp: 'अॅप शेअर करा',
      deleteAccount: 'खाते हटवा',
      deleteAccountWarning: 'ही क्रिया पूर्ववत केली जाऊ शकत नाही',
      nameRequired: 'नाव आवश्यक आहे',
      phoneInvalid: 'अवैध फोन नंबर',
      urlInvalid: 'अवैध URL',
      saveSuccess: 'प्रोफाइल यशस्वीरित्या अपडेट केली',
      saveError: 'प्रोफाइल अपडेट करण्यात अयशस्वी',
    },
    auth: {
      login: 'लॉगिन',
      signUp: 'साइन अप',
      email: 'ईमेल',
      password: 'पासवर्ड',
      confirmPassword: 'पासवर्डची पुष्टी करा',
      forgotPassword: 'पासवर्ड विसरलात?',
      continueAsGuest: 'पाहुणा म्हणून सुरू ठेवा',
      dontHaveAccount: 'खाते नाही?',
      alreadyHaveAccount: 'आधीपासून खाते आहे?',
      createAccount: 'खाते तयार करा',
      otpVerification: 'OTP सत्यापन',
      otpSent: 'OTP तुमच्या ईमेलवर पाठवला आहे',
      enterOTP: 'OTP प्रविष्ट करा',
      verify: 'सत्यापित करा',
      resendOTP: 'OTP पुन्हा पाठवा',
      personalDetails: 'वैयक्तिक तपशील',
      uploadPhoto: 'फोटो अपलोड करा',
      takePhoto: 'फोटो काढा',
      chooseFromGallery: 'गॅलरीमधून निवडा',
      continue: 'सुरू ठेवा',
      emailRequired: 'ईमेल आवश्यक आहे',
      emailInvalid: 'अवैध ईमेल स्वरूप',
      passwordRequired: 'पासवर्ड आवश्यक आहे',
      passwordMinLength: 'पासवर्ड किमान 6 वर्णांचा असावा',
      passwordMismatch: 'पासवर्ड जुळत नाहीत',
      otpRequired: 'OTP आवश्यक आहे',
      otpInvalid: 'अवैध OTP',
      nameRequired: 'नाव आवश्यक आहे',
      loginSuccess: 'लॉगिन यशस्वी',
      loginError: 'लॉगिन अयशस्वी',
      signUpSuccess: 'खाते यशस्वीरित्या तयार केले',
      signUpError: 'साइन अप अयशस्वी',
      otpSuccess: 'OTP यशस्वीरित्या सत्यापित केले',
      otpError: 'OTP सत्यापन अयशस्वी',
      resetPasswordDescription:
        'अपना ईमेल पता दर्ज करें और हम आपको पासवर्ड रीसेट करने के लिए एक लिंक भेजेंगे।',
      sendResetLink: 'रीसेट लिंक भेजें',
      resetPasswordEmailSent: 'ईमेल भेजा गया!',
      resetPasswordCheckEmail:
        'कृपया पासवर्ड रीसेट निर्देशों के लिए अपना ईमेल जांचें। लिंक 1 घंटे में समाप्त हो जाएगा।',
      resetPasswordError: 'रीसेट ईमेल भेजने में विफल',
      rememberPassword: 'अपना पासवर्ड याद है?',
      backToLogin: 'लॉगिन पर वापस जाएं',
    },
  },
  ta: {
    intro: {
      skip: 'தவிர்க்க',
      next: 'அடுத்து',
      getStarted: 'தொடங்க',
      welcome: 'SharePost-க்கு வரவேற்கிறோம்',
      subtitle:
        'புகைப்படங்கள், தீம்கள் மற்றும் பலவற்றுடன் அழகான இடுகைகளை உருவாக்கவும்',
    },
    common: {
      continue: 'தொடர',
      cancel: 'ரத்துசெய்',
      save: 'சேமி',
      delete: 'நீக்கு',
      edit: 'திருத்து',
      share: 'பகிர்',
    },
    features: {
      addPhotos: 'உங்கள் புகைப்படங்களைச் சேர்க்கவும்',
      addPhotosDesc:
        'அழகான பின்னணிகளுடன் உங்கள் விருப்பமான புகைப்படங்களை பதிவேற்றவும் மற்றும் பகிரவும்',
      personalize: 'உங்கள் சுயவிவரத்தை தனிப்பயனாக்கவும்',
      personalizeDesc:
        'மற்றவர்களுடன் இணைக்க உங்கள் பெயர் மற்றும் சமூக ஊடக இணைப்புகளைச் சேர்க்கவும்',
      celebrate: 'சிறப்பு நாட்களை கொண்டாடுங்கள்',
      celebrateDesc:
        'குடியரசு தினம், திருவிழாக்கள் மற்றும் ஊக்கமளிக்கும் எண்ணங்கள் போன்ற தீம்களிலிருந்து தேர்வு செய்யவும்',
      share: 'பகிர்ந்து ஊக்குவிக்கவும்',
      shareDesc:
        'அழகான இடுகைகளை உருவாக்கி அவற்றை உங்கள் நண்பர்கள் மற்றும் குடும்பத்தினருடன் பகிரவும்',
    },
    language: {
      title: 'மொழியைத் தேர்ந்தெடுக்கவும்',
      subtitle: 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
      currentLanguage: 'தற்போதைய மொழி',
      continue: 'தொடர',
    },
    home: {
      title: 'வீடு',
      welcome: 'வரவேற்பு',
      welcomeUser: 'வரவேற்பு பயனர்',
      goodMorning: 'காலை வணக்கம்',
      goodAfternoon: 'மதிய வணக்கம்',
      goodEvening: 'மாலை வணக்கம்',
      searchPlaceholder: 'தேடு...',
      selectCategory: 'வகையைத் தேர்ந்தெடுக்கவும்',
      createPost: 'இடுகையை உருவாக்கவும்',
      myPosts: 'எனது இடுகைகள்',
      noPosts: 'இன்னும் இடுகைகள் இல்லை',
      createFirstPost: 'தொடங்க உங்கள் முதல் இடுகையை உருவாக்கவும்',
      categories: {
        all: 'அனைத்தும்',
        newYear: 'புத்தாண்டு',
        goodMorning: 'காலை வணக்கம்',
        goodNight: 'இரவு வணக்கம்',
        suvichar: 'சுயிச்சார்',
      },
      download: 'பதிவிறக்க',
      edit: 'திருத்து',
      more: 'மேலும்',
      customize: 'தனிப்பயனாக்க',
    },
    settings: {
      title: 'அமைப்புகள்',
      profile: 'சுயவிவரம்',
      language: 'மொழி',
      theme: 'தீம்',
      darkMode: 'இருண்ட முறை',
      lightMode: 'ஒளி முறை',
      about: 'பற்றி',
      logout: 'வெளியேற',
      version: 'பதிப்பு',
    },
    profile: {
      title: 'சுயவிவரம்',
      editProfile: 'சுயவிவரத்தை திருத்து',
      fullName: 'முழு பெயர்',
      phoneNumber: 'தொலைபேசி எண்',
      bio: 'உயிர் / விளக்கம்',
      facebook: 'பேஸ்புக்',
      instagram: 'இன்ஸ்டாகிராம்',
      twitter: 'ட்விட்டர்',
      save: 'சேமி',
      cancel: 'ரத்துசெய்',
      faq: 'FAQ',
      terms: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      privacy: 'தனியுரிமை கொள்கை',
      subscriptions: 'சந்தா',
      shareApp: 'ஆப் பகிர்',
      deleteAccount: 'கணக்கை நீக்கு',
      deleteAccountWarning: 'இந்த செயலை திரும்பப் பெற முடியாது',
      nameRequired: 'பெயர் தேவை',
      phoneInvalid: 'தவறான தொலைபேசி எண்',
      urlInvalid: 'தவறான URL',
      saveSuccess: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      saveError: 'சுயவிவரத்தை புதுப்பிக்க முடியவில்லை',
    },
    auth: {
      login: 'உள்நுழை',
      signUp: 'பதிவு செய்',
      email: 'மின்னஞ்சல்',
      password: 'கடவுச்சொல்',
      confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
      forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
      continueAsGuest: 'விருந்தினராக தொடர',
      dontHaveAccount: 'கணக்கு இல்லையா?',
      alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
      createAccount: 'கணக்கு உருவாக்க',
      otpVerification: 'OTP சரிபார்ப்பு',
      otpSent: 'OTP உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டது',
      enterOTP: 'OTP உள்ளிடவும்',
      verify: 'சரிபார்',
      resendOTP: 'OTP மீண்டும் அனுப்ப',
      personalDetails: 'தனிப்பட்ட விவரங்கள்',
      uploadPhoto: 'புகைப்படம் பதிவேற்ற',
      takePhoto: 'புகைப்படம் எடு',
      chooseFromGallery: 'கேலரியிலிருந்து தேர்ந்தெடு',
      continue: 'தொடர',
      emailRequired: 'மின்னஞ்சல் தேவை',
      emailInvalid: 'தவறான மின்னஞ்சல் வடிவம்',
      passwordRequired: 'கடவுச்சொல் தேவை',
      passwordMinLength: 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
      passwordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
      otpRequired: 'OTP தேவை',
      otpInvalid: 'தவறான OTP',
      nameRequired: 'பெயர் தேவை',
      loginSuccess: 'உள்நுழைவு வெற்றிகரமானது',
      loginError: 'உள்நுழைவு தோல்வி',
      signUpSuccess: 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
      signUpError: 'பதிவு தோல்வி',
      otpSuccess: 'OTP வெற்றிகரமாக சரிபார்க்கப்பட்டது',
      otpError: 'OTP சரிபார்ப்பு தோல்வி',
      resetPasswordDescription:
        'உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும், உங்கள் கடவுச்சொல்லை மீட்டமைக்க ஒரு இணைப்பை அனுப்புவோம்.',
      sendResetLink: 'மீட்டமைப்பு இணைப்பை அனுப்பவும்',
      resetPasswordEmailSent: 'மின்னஞ்சல் அனுப்பப்பட்டது!',
      resetPasswordCheckEmail:
        'கடவுச்சொல் மீட்டமைப்பு வழிமுறைகளுக்காக உங்கள் மின்னஞ்சலை சரிபார்க்கவும். இணைப்பு 1 மணி நேரத்தில் காலாவதியாகும்.',
      resetPasswordError: 'மீட்டமைப்பு மின்னஞ்சலை அனுப்ப முடியவில்லை',
      rememberPassword: 'உங்கள் கடவுச்சொல் நினைவிருக்கிறதா?',
      backToLogin: 'உள்நுழைவுக்குத் திரும்பு',
    },
  },
  te: {
    intro: {
      skip: 'దాటవేయి',
      next: 'తదుపరి',
      getStarted: 'ప్రారంభించండి',
      welcome: 'SharePost కు స్వాగతం',
      subtitle:
        'ఫోటోలు, థీమ్లు మరియు మరిన్ని వాటితో అందమైన పోస్ట్లను సృష్టించండి',
    },
    common: {
      continue: 'కొనసాగించు',
      cancel: 'రద్దు చేయి',
      save: 'సేవ్ చేయి',
      delete: 'తొలగించు',
      edit: 'సవరించు',
      share: 'షేర్ చేయి',
    },
    features: {
      addPhotos: 'మీ ఫోటోలను జోడించండి',
      addPhotosDesc:
        'అందమైన నేపథ్యాలతో మీకు ఇష్టమైన ఫోటోలను అప్లోడ్ చేసి షేర్ చేయండి',
      personalize: 'మీ ప్రొఫైల్ను వ్యక్తిగతీకరించండి',
      personalizeDesc:
        'ఇతరులతో కనెక్ట్ కావడానికి మీ పేరు మరియు సోషల్ మీడియా లింక్లను జోడించండి',
      celebrate: 'ప్రత్యేక రోజులను జరుపుకోండి',
      celebrateDesc:
        'రిపబ్లిక్ డే, పండుగలు మరియు ప్రేరణాత్మక ఆలోచనల వంటి థీమ్ల నుండి ఎంచుకోండి',
      share: 'షేర్ చేసి ప్రేరణ ఇవ్వండి',
      shareDesc:
        'అందమైన పోస్ట్లను సృష్టించి వాటిని మీ స్నేహితులు మరియు కుటుంబంతో షేర్ చేయండి',
    },
    language: {
      title: 'భాషను ఎంచుకోండి',
      subtitle: 'మీకు ఇష్టమైన భాషను ఎంచుకోండి',
      selectLanguage: 'భాషను ఎంచుకోండి',
      currentLanguage: 'ప్రస్తుత భాష',
      continue: 'కొనసాగించు',
    },
    home: {
      title: 'హోమ్',
      welcome: 'స్వాగతం',
      welcomeUser: 'స్వాగతం యూజర్',
      goodMorning: 'శుభోదయం',
      goodAfternoon: 'నమస్కారం',
      goodEvening: 'శుభ సాయంత్రం',
      searchPlaceholder: 'శోధించు...',
      selectCategory: 'వర్గాన్ని ఎంచుకోండి',
      createPost: 'పోస్ట్ సృష్టించండి',
      myPosts: 'నా పోస్ట్లు',
      noPosts: 'ఇంకా పోస్ట్లు లేవు',
      createFirstPost: 'ప్రారంభించడానికి మీ మొదటి పోస్ట్ను సృష్టించండి',
      categories: {
        all: 'అన్నీ',
        newYear: 'నూతన సంవత్సరం',
        goodMorning: 'శుభోదయం',
        goodNight: 'శుభ రాత్రి',
        suvichar: 'సువిచార్',
      },
      download: 'డౌన్‌లోడ్',
      edit: 'సవరించు',
      more: 'మరిన్ని',
      customize: 'అనుకూలీకరించు',
    },
    settings: {
      title: 'సెట్టింగ్స్',
      profile: 'ప్రొఫైల్',
      language: 'భాష',
      theme: 'థీమ్',
      darkMode: 'డార్క్ మోడ్',
      lightMode: 'లైట్ మోడ్',
      about: 'గురించి',
      logout: 'లాగ్అవుట్',
      version: 'వెర్షన్',
    },
    profile: {
      title: 'ప్రొఫైల్',
      editProfile: 'ప్రొఫైల్ సవరించు',
      fullName: 'పూర్తి పేరు',
      phoneNumber: 'ఫోన్ నంబర్',
      bio: 'బయో / వివరణ',
      facebook: 'ఫేస్బుక్',
      instagram: 'ఇన్స్టాగ్రామ్',
      twitter: 'ట్విట్టర్',
      save: 'సేవ్ చేయి',
      cancel: 'రద్దు చేయి',
      faq: 'FAQ',
      terms: 'నిబంధనలు మరియు షరతులు',
      privacy: 'గోప్యతా విధానం',
      subscriptions: 'సభ్యత్వం',
      shareApp: 'అనువర్తనాన్ని షేర్ చేయండి',
      deleteAccount: 'ఖాతాను తొలగించు',
      deleteAccountWarning: 'ఈ చర్యను రద్దు చేయలేము',
      nameRequired: 'పేరు అవసరం',
      phoneInvalid: 'చెల్లని ఫోన్ నంబర్',
      urlInvalid: 'చెల్లని URL',
      saveSuccess: 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది',
      saveError: 'ప్రొఫైల్ నవీకరించడంలో విఫలమైంది',
    },
    auth: {
      login: 'లాగిన్',
      signUp: 'సైన్ అప్',
      email: 'ఇమెయిల్',
      password: 'పాస్వర్డ్',
      confirmPassword: 'పాస్వర్డ్ నిర్ధారించండి',
      forgotPassword: 'పాస్వర్డ్ మర్చిపోయారా?',
      continueAsGuest: 'అతిథిగా కొనసాగించండి',
      dontHaveAccount: 'ఖాతా లేదా?',
      alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
      createAccount: 'ఖాతా సృష్టించండి',
      otpVerification: 'OTP ధృవీకరణ',
      otpSent: 'OTP మీ ఇమెయిల్‌కు పంపబడింది',
      enterOTP: 'OTP నమోదు చేయండి',
      verify: 'ధృవీకరించండి',
      resendOTP: 'OTP మళ్లీ పంపండి',
      personalDetails: 'వ్యక్తిగత వివరాలు',
      uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
      takePhoto: 'ఫోటో తీయండి',
      chooseFromGallery: 'గ్యాలరీ నుండి ఎంచుకోండి',
      continue: 'కొనసాగించండి',
      emailRequired: 'ఇమెయిల్ అవసరం',
      emailInvalid: 'చెల్లని ఇమెయిల్ ఫార్మాట్',
      passwordRequired: 'పాస్వర్డ్ అవసరం',
      passwordMinLength: 'పాస్వర్డ్ కనీసం 6 అక్షరాలుగా ఉండాలి',
      passwordMismatch: 'పాస్వర్డ్‌లు సరిపోలడం లేదు',
      otpRequired: 'OTP అవసరం',
      otpInvalid: 'చెల్లని OTP',
      nameRequired: 'పేరు అవసరం',
      loginSuccess: 'లాగిన్ విజయవంతమైంది',
      loginError: 'లాగిన్ విఫలమైంది',
      signUpSuccess: 'ఖాతా విజయవంతంగా సృష్టించబడింది',
      signUpError: 'సైన్ అప్ విఫలమైంది',
      otpSuccess: 'OTP విజయవంతంగా ధృవీకరించబడింది',
      otpError: 'OTP ధృవీకరణ విఫలమైంది',
      resetPasswordDescription:
        'మీ ఇమెయిల్ చిరునామాను నమోదు చేయండి మరియు మేము మీ పాస్వర్డ్ను రీసెట్ చేయడానికి లింక్‌ను పంపుతాము.',
      sendResetLink: 'రీసెట్ లింక్ పంపండి',
      resetPasswordEmailSent: 'ఇమెయిల్ పంపబడింది!',
      resetPasswordCheckEmail:
        'దయచేసి పాస్వర్డ్ రీసెట్ సూచనల కోసం మీ ఇమెయిల్‌ను తనిఖీ చేయండి. లింక్ 1 గంటలో గడువు ముగుస్తుంది.',
      resetPasswordError: 'రీసెట్ ఇమెయిల్ పంపడంలో విఫలమైంది',
      rememberPassword: 'మీ పాస్వర్డ్ గుర్తుందా?',
      backToLogin: 'లాగిన్‌కు తిరిగి వెళ్ళండి',
    },
  },
  kn: {
    intro: {
      skip: 'ಬಿಟ್ಟುಬಿಡಿ',
      next: 'ಮುಂದೆ',
      getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
      welcome: 'SharePost ಗೆ ಸ್ವಾಗತ',
      subtitle:
        'ಫೋಟೋಗಳು, ಥೀಮ್ಗಳು ಮತ್ತು ಹೆಚ್ಚಿನವುಗಳೊಂದಿಗೆ ಸುಂದರ ಪೋಸ್ಟ್ಗಳನ್ನು ರಚಿಸಿ',
    },
    common: {
      continue: 'ಮುಂದುವರಿಸಿ',
      cancel: 'ರದ್ದುಮಾಡಿ',
      save: 'ಉಳಿಸಿ',
      delete: 'ಅಳಿಸಿ',
      edit: 'ಸಂಪಾದಿಸಿ',
      share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    },
    features: {
      addPhotos: 'ನಿಮ್ಮ ಫೋಟೋಗಳನ್ನು ಸೇರಿಸಿ',
      addPhotosDesc:
        'ಸುಂದರ ಹಿನ್ನೆಲೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ನೆಚ್ಚಿನ ಫೋಟೋಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಹಂಚಿಕೊಳ್ಳಿ',
      personalize: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಿ',
      personalizeDesc:
        'ಇತರರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲು ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಲಿಂಕ್ಗಳನ್ನು ಸೇರಿಸಿ',
      celebrate: 'ವಿಶೇಷ ದಿನಗಳನ್ನು ಆಚರಿಸಿ',
      celebrateDesc:
        'ರಿಪಬ್ಲಿಕ್ ಡೇ, ಹಬ್ಬಗಳು ಮತ್ತು ಪ್ರೇರಣಾದಾಯಕ ಆಲೋಚನೆಗಳಂತಹ ಥೀಮ್ಗಳಿಂದ ಆಯ್ಕೆ ಮಾಡಿ',
      share: 'ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ಪ್ರೇರೇಪಿಸಿ',
      shareDesc:
        'ಸುಂದರ ಪೋಸ್ಟ್ಗಳನ್ನು ರಚಿಸಿ ಮತ್ತು ಅವುಗಳನ್ನು ನಿಮ್ಮ ಸ್ನೇಹಿತರು ಮತ್ತು ಕುಟುಂಬದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ',
    },
    language: {
      title: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      subtitle: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      currentLanguage: 'ಪ್ರಸ್ತುತ ಭಾಷೆ',
      continue: 'ಮುಂದುವರಿಸಿ',
    },
    home: {
      title: 'ಮುಖಪುಟ',
      welcome: 'ಸ್ವಾಗತ',
      welcomeUser: 'ಸ್ವಾಗತ ಬಳಕೆದಾರ',
      goodMorning: 'ಶುಭೋದಯ',
      goodAfternoon: 'ನಮಸ್ಕಾರ',
      goodEvening: 'ಶುಭ ಸಂಜೆ',
      searchPlaceholder: 'ಹುಡುಕಿ...',
      selectCategory: 'ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      createPost: 'ಪೋಸ್ಟ್ ರಚಿಸಿ',
      myPosts: 'ನನ್ನ ಪೋಸ್ಟ್ಗಳು',
      noPosts: 'ಇನ್ನೂ ಪೋಸ್ಟ್ಗಳು ಇಲ್ಲ',
      createFirstPost: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಪೋಸ್ಟ್ ಅನ್ನು ರಚಿಸಿ',
      categories: {
        all: 'ಎಲ್ಲಾ',
        newYear: 'ಹೊಸ ವರ್ಷ',
        goodMorning: 'ಶುಭೋದಯ',
        goodNight: 'ಶುಭ ರಾತ್ರಿ',
        suvichar: 'ಸುವಿಚಾರ್',
      },
      download: 'ಡೌನ್‌ಲೋಡ್',
      edit: 'ಸಂಪಾದಿಸಿ',
      more: 'ಹೆಚ್ಚು',
      customize: 'ಕಸ್ಟಮೈಸ್ ಮಾಡಿ',
    },
    settings: {
      title: 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
      profile: 'ಪ್ರೊಫೈಲ್',
      language: 'ಭಾಷೆ',
      theme: 'ಥೀಮ್',
      darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
      lightMode: 'ಲೈಟ್ ಮೋಡ್',
      about: 'ಬಗ್ಗೆ',
      logout: 'ಲಾಗ್ ಔಟ್',
      version: 'ಆವೃತ್ತಿ',
    },
    profile: {
      title: 'ಪ್ರೊಫೈಲ್',
      editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      fullName: 'ಪೂರ್ಣ ಹೆಸರು',
      phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
      bio: 'ಬಯೋ / ವಿವರಣೆ',
      facebook: 'ಫೇಸ್ಬುಕ್',
      instagram: 'ಇನ್ಸ್ಟಾಗ್ರಾಮ್',
      twitter: 'ಟ್ವಿಟರ್',
      save: 'ಉಳಿಸಿ',
      cancel: 'ರದ್ದುಮಾಡಿ',
      faq: 'FAQ',
      terms: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
      privacy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
      subscriptions: 'ಚಂದಾದಾರಿಕೆ',
      shareApp: 'ಅಪ್ಲಿಕೇಶನ್ ಹಂಚಿಕೊಳ್ಳಿ',
      deleteAccount: 'ಖಾತೆಯನ್ನು ಅಳಿಸಿ',
      deleteAccountWarning: 'ಈ ಕ್ರಿಯೆಯನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗುವುದಿಲ್ಲ',
      nameRequired: 'ಹೆಸರು ಅಗತ್ಯವಿದೆ',
      phoneInvalid: 'ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ',
      urlInvalid: 'ಅಮಾನ್ಯ URL',
      saveSuccess: 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
      saveError: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ',
    },
    auth: {
      login: 'ಲಾಗಿನ್',
      signUp: 'ಸೈನ್ ಅಪ್',
      email: 'ಇಮೇಲ್',
      password: 'ಪಾಸ್ವರ್ಡ್',
      confirmPassword: 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
      forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರುವಿರಾ?',
      continueAsGuest: 'ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಸಿ',
      dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
      alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
      createAccount: 'ಖಾತೆ ರಚಿಸಿ',
      otpVerification: 'OTP ಪರಿಶೀಲನೆ',
      otpSent: 'OTP ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
      enterOTP: 'OTP ನಮೂದಿಸಿ',
      verify: 'ಪರಿಶೀಲಿಸಿ',
      resendOTP: 'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',
      personalDetails: 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
      uploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      takePhoto: 'ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
      chooseFromGallery: 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ',
      continue: 'ಮುಂದುವರಿಸಿ',
      emailRequired: 'ಇಮೇಲ್ ಅಗತ್ಯವಿದೆ',
      emailInvalid: 'ಅಮಾನ್ಯ ಇಮೇಲ್ ಸ್ವರೂಪ',
      passwordRequired: 'ಪಾಸ್ವರ್ಡ್ ಅಗತ್ಯವಿದೆ',
      passwordMinLength: 'ಪಾಸ್ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು',
      passwordMismatch: 'ಪಾಸ್ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ',
      otpRequired: 'OTP ಅಗತ್ಯವಿದೆ',
      otpInvalid: 'ಅಮಾನ್ಯ OTP',
      nameRequired: 'ಹೆಸರು ಅಗತ್ಯವಿದೆ',
      loginSuccess: 'ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ',
      loginError: 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
      signUpSuccess: 'ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ',
      signUpError: 'ಸೈನ್ ಅಪ್ ವಿಫಲವಾಗಿದೆ',
      otpSuccess: 'OTP ಯಶಸ್ವಿಯಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      otpError: 'OTP ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ',
      resetPasswordDescription:
        'ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ನಾವು ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ಅನ್ನು ಮರುಹೊಂದಿಸಲು ಲಿಂಕ್ ಅನ್ನು ಕಳುಹಿಸುತ್ತೇವೆ.',
      sendResetLink: 'ಮರುಹೊಂದಿಸಿ ಲಿಂಕ್ ಕಳುಹಿಸಿ',
      resetPasswordEmailSent: 'ಇಮೇಲ್ ಕಳುಹಿಸಲಾಗಿದೆ!',
      resetPasswordCheckEmail:
        'ದಯವಿಟ್ಟು ಪಾಸ್ವರ್ಡ್ ಮರುಹೊಂದಿಸುವ ಸೂಚನೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ. ಲಿಂಕ್ 1 ಗಂಟೆಯಲ್ಲಿ ಮುಕ್ತಾಯಗೊಳ್ಳುತ್ತದೆ.',
      resetPasswordError: 'ಮರುಹೊಂದಿಸಿ ಇಮೇಲ್ ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ',
      rememberPassword: 'ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನೆನಪಿದೆಯೇ?',
      backToLogin: 'ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    },
  },
  ml: {
    intro: {
      skip: 'ഒഴിവാക്കുക',
      next: 'അടുത്തത്',
      getStarted: 'ആരംഭിക്കുക',
      welcome: 'SharePost-ലേക്ക് സ്വാഗതം',
      subtitle:
        'ഫോട്ടോകൾ, തീമുകൾ, മറ്റുള്ളവ എന്നിവ ഉപയോഗിച്ച് മനോഹരമായ പോസ്റ്റുകൾ സൃഷ്ടിക്കുക',
    },
    common: {
      continue: 'തുടരുക',
      cancel: 'റദ്ദാക്കുക',
      save: 'സേവ് ചെയ്യുക',
      delete: 'ഇല്ലാതാക്കുക',
      edit: 'എഡിറ്റ് ചെയ്യുക',
      share: 'പങ്കിടുക',
    },
    features: {
      addPhotos: 'നിങ്ങളുടെ ഫോട്ടോകൾ ചേർക്കുക',
      addPhotosDesc:
        'മനോഹരമായ പശ്ചാത്തലങ്ങളുള്ള നിങ്ങളുടെ പ്രിയപ്പെട്ട ഫോട്ടോകൾ അപ്‌ലോഡ് ചെയ്ത് പങ്കിടുക',
      personalize: 'നിങ്ങളുടെ പ്രൊഫൈൽ വ്യക്തിഗതമാക്കുക',
      personalizeDesc:
        'മറ്റുള്ളവരുമായി ബന്ധപ്പെടാൻ നിങ്ങളുടെ പേരും സോഷ്യൽ മീഡിയ ലിങ്കുകളും ചേർക്കുക',
      celebrate: 'പ്രത്യേക ദിവസങ്ങൾ ആഘോഷിക്കുക',
      celebrateDesc:
        'റിപ്പബ്ലിക് ഡേ, ഉത്സവങ്ങൾ, പ്രചോദനാത്മക ചിന്തകൾ തുടങ്ങിയ തീമുകളിൽ നിന്ന് തിരഞ്ഞെടുക്കുക',
      share: 'പങ്കിടുകയും പ്രചോദിപ്പിക്കുകയും ചെയ്യുക',
      shareDesc:
        'മനോഹരമായ പോസ്റ്റുകൾ സൃഷ്ടിച്ച് അവ നിങ്ങളുടെ സുഹൃത്തുക്കളുമായും കുടുംബത്തിലെ അംഗങ്ങളുമായും പങ്കിടുക',
    },
    language: {
      title: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      subtitle: 'നിങ്ങളുടെ പ്രിയപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക',
      selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      currentLanguage: 'നിലവിലെ ഭാഷ',
      continue: 'തുടരുക',
    },
    home: {
      title: 'ഹോം',
      welcome: 'സ്വാഗതം',
      welcomeUser: 'സ്വാഗതം ഉപയോക്താവ്',
      goodMorning: 'സുപ്രഭാതം',
      goodAfternoon: 'നമസ്കാരം',
      goodEvening: 'ശുഭ സന്ധ്യ',
      searchPlaceholder: 'തിരയുക...',
      selectCategory: 'വിഭാഗം തിരഞ്ഞെടുക്കുക',
      createPost: 'പോസ്റ്റ് സൃഷ്ടിക്കുക',
      myPosts: 'എന്റെ പോസ്റ്റുകൾ',
      noPosts: 'ഇതുവരെ പോസ്റ്റുകൾ ഇല്ല',
      createFirstPost: 'ആരംഭിക്കാൻ നിങ്ങളുടെ ആദ്യ പോസ്റ്റ് സൃഷ്ടിക്കുക',
      categories: {
        all: 'എല്ലാം',
        newYear: 'പുതുവർഷം',
        goodMorning: 'സുപ്രഭാതം',
        goodNight: 'ശുഭ രാത്രി',
        suvichar: 'സുവിചാര്',
      },
      download: 'ഡൗൺലോഡ്',
      edit: 'എഡിറ്റ് ചെയ്യുക',
      more: 'കൂടുതൽ',
      customize: 'ഇഷ്ടാനുസൃതമാക്കുക',
    },
    settings: {
      title: 'സെറ്റിംഗുകൾ',
      profile: 'പ്രൊഫൈൽ',
      language: 'ഭാഷ',
      theme: 'തീം',
      darkMode: 'ഡാർക്ക് മോഡ്',
      lightMode: 'ലൈറ്റ് മോഡ്',
      about: 'കുറിച്ച്',
      logout: 'ലോഗ് ഔട്ട്',
      version: 'പതിപ്പ്',
    },
    profile: {
      title: 'പ്രൊഫൈൽ',
      editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      fullName: 'പൂർണ്ണ നാമം',
      phoneNumber: 'ഫോൺ നമ്പർ',
      bio: 'ബയോ / വിവരണം',
      facebook: 'ഫേസ്ബുക്ക്',
      instagram: 'ഇൻസ്റ്റാഗ്രാം',
      twitter: 'ട്വിറ്റർ',
      save: 'സേവ് ചെയ്യുക',
      cancel: 'റദ്ദാക്കുക',
      faq: 'FAQ',
      terms: 'നിബന്ധനകളും വ്യവസ്ഥകളും',
      privacy: 'സ്വകാര്യതാ നയം',
      subscriptions: 'സബ്സ്ക്രിപ്ഷൻ',
      shareApp: 'ആപ്പ് പങ്കിടുക',
      deleteAccount: 'അക്കൗണ്ട് ഇല്ലാതാക്കുക',
      deleteAccountWarning: 'ഈ പ്രവർത്തനം പൂർവ്വസ്ഥയിലാക്കാൻ കഴിയില്ല',
      nameRequired: 'നാമം ആവശ്യമാണ്',
      phoneInvalid: 'അസാധുവായ ഫോൺ നമ്പർ',
      urlInvalid: 'അസാധുവായ URL',
      saveSuccess: 'പ്രൊഫൈൽ വിജയകരമായി അപ്ഡേറ്റ് ചെയ്തു',
      saveError: 'പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു',
    },
    auth: {
      login: 'ലോഗിൻ',
      signUp: 'സൈൻ അപ്പ്',
      email: 'ഇമെയിൽ',
      password: 'പാസ്‌വേഡ്',
      confirmPassword: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
      forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
      continueAsGuest: 'അതിഥിയായി തുടരുക',
      dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
      alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
      createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      otpVerification: 'OTP പരിശോധന',
      otpSent: 'OTP നിങ്ങളുടെ ഇമെയിലിലേക്ക് അയച്ചു',
      enterOTP: 'OTP നൽകുക',
      verify: 'പരിശോധിക്കുക',
      resendOTP: 'OTP വീണ്ടും അയയ്ക്കുക',
      personalDetails: 'വ്യക്തിഗത വിശദാംശങ്ങൾ',
      uploadPhoto: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
      takePhoto: 'ഫോട്ടോ എടുക്കുക',
      chooseFromGallery: 'ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക',
      continue: 'തുടരുക',
      emailRequired: 'ഇമെയിൽ ആവശ്യമാണ്',
      emailInvalid: 'അസാധുവായ ഇമെയിൽ ഫോർമാറ്റ്',
      passwordRequired: 'പാസ്‌വേഡ് ആവശ്യമാണ്',
      passwordMinLength: 'പാസ്‌വേഡ് കുറഞ്ഞത് 6 അക്ഷരങ്ങളായിരിക്കണം',
      passwordMismatch: 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല',
      otpRequired: 'OTP ആവശ്യമാണ്',
      otpInvalid: 'അസാധുവായ OTP',
      nameRequired: 'പേര് ആവശ്യമാണ്',
      loginSuccess: 'ലോഗിൻ വിജയകരമാണ്',
      loginError: 'ലോഗിൻ പരാജയപ്പെട്ടു',
      signUpSuccess: 'അക്കൗണ്ട് വിജയകരമായി സൃഷ്ടിച്ചു',
      signUpError: 'സൈൻ അപ്പ് പരാജയപ്പെട്ടു',
      otpSuccess: 'OTP വിജയകരമായി പരിശോധിച്ചു',
      otpError: 'OTP പരിശോധന പരാജയപ്പെട്ടു',
      resetPasswordDescription:
        'നിങ്ങളുടെ ഇമെയിൽ വിലാസം നൽകുക, ഞങ്ങൾ നിങ്ങളുടെ പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യുന്നതിന് ഒരു ലിങ്ക് അയയ്ക്കും.',
      sendResetLink: 'റീസെറ്റ് ലിങ്ക് അയയ്ക്കുക',
      resetPasswordEmailSent: 'ഇമെയിൽ അയച്ചു!',
      resetPasswordCheckEmail:
        'ദയവായി പാസ്‌വേഡ് റീസെറ്റ് നിർദ്ദേശങ്ങൾക്കായി നിങ്ങളുടെ ഇമെയിൽ പരിശോധിക്കുക. ലിങ്ക് 1 മണിക്കൂറിനുള്ളിൽ കാലഹരണപ്പെടും.',
      resetPasswordError: 'റീസെറ്റ് ഇമെയിൽ അയയ്ക്കുന്നതിൽ പരാജയപ്പെട്ടു',
      rememberPassword: 'നിങ്ങളുടെ പാസ്‌വേഡ് ഓർമ്മയുണ്ടോ?',
      backToLogin: 'ലോഗിൻ‌ലേക്ക് തിരികെ പോകുക',
    },
  },
  bn: {
    intro: {
      skip: 'এড়িয়ে যান',
      next: 'পরবর্তী',
      getStarted: 'শুরু করুন',
      welcome: 'SharePost-এ স্বাগতম',
      subtitle: 'ছবি, থিম এবং আরও অনেক কিছু দিয়ে সুন্দর পোস্ট তৈরি করুন',
    },
    common: {
      continue: 'চালিয়ে যান',
      cancel: 'বাতিল',
      save: 'সংরক্ষণ',
      delete: 'মুছুন',
      edit: 'সম্পাদনা',
      share: 'শেয়ার',
    },
    features: {
      addPhotos: 'আপনার ছবি যোগ করুন',
      addPhotosDesc:
        'সুন্দর ব্যাকগ্রাউন্ড সহ আপনার প্রিয় ছবি আপলোড করুন এবং শেয়ার করুন',
      personalize: 'আপনার প্রোফাইল ব্যক্তিগত করুন',
      personalizeDesc:
        'অন্যদের সাথে সংযুক্ত হতে আপনার নাম এবং সোশ্যাল মিডিয়া লিঙ্ক যোগ করুন',
      celebrate: 'বিশেষ দিন উদযাপন করুন',
      celebrateDesc:
        'প্রজাতন্ত্র দিবস, উৎসব এবং অনুপ্রেরণামূলক চিন্তাভাবনার মতো থিম থেকে বেছে নিন',
      share: 'শেয়ার করুন এবং অনুপ্রাণিত করুন',
      shareDesc:
        'সুন্দর পোস্ট তৈরি করুন এবং সেগুলি আপনার বন্ধু এবং পরিবারের সাথে শেয়ার করুন',
    },
    language: {
      title: 'ভাষা নির্বাচন করুন',
      subtitle: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
      selectLanguage: 'ভাষা নির্বাচন করুন',
      currentLanguage: 'বর্তমান ভাষা',
      continue: 'চালিয়ে যান',
    },
    home: {
      title: 'হোম',
      welcome: 'স্বাগতম',
      welcomeUser: 'স্বাগতম ব্যবহারকারী',
      goodMorning: 'সুপ্রভাত',
      goodAfternoon: 'নমস্কার',
      goodEvening: 'শুভ সন্ধ্যা',
      searchPlaceholder: 'অনুসন্ধান করুন...',
      selectCategory: 'বিভাগ নির্বাচন করুন',
      createPost: 'পোস্ট তৈরি করুন',
      myPosts: 'আমার পোস্ট',
      noPosts: 'এখনও কোন পোস্ট নেই',
      createFirstPost: 'শুরু করতে আপনার প্রথম পোস্ট তৈরি করুন',
      categories: {
        all: 'সব',
        newYear: 'নববর্ষ',
        goodMorning: 'সুপ্রভাত',
        goodNight: 'শুভ রাত্রি',
        suvichar: 'সুভিচার',
      },
      download: 'ডাউনলোড',
      edit: 'সম্পাদনা',
      more: 'আরও',
      customize: 'কাস্টমাইজ করুন',
    },
    settings: {
      title: 'সেটিংস',
      profile: 'প্রোফাইল',
      language: 'ভাষা',
      theme: 'থিম',
      darkMode: 'ডার্ক মোড',
      lightMode: 'লাইট মোড',
      about: 'সম্পর্কে',
      logout: 'লগআউট',
      version: 'সংস্করণ',
    },
    profile: {
      title: 'প্রোফাইল',
      editProfile: 'প্রোফাইল সম্পাদনা করুন',
      fullName: 'পূর্ণ নাম',
      phoneNumber: 'ফোন নম্বর',
      bio: 'বায়ো / বিবরণ',
      facebook: 'ফেসবুক',
      instagram: 'ইনস্টাগ্রাম',
      twitter: 'টুইটার',
      save: 'সংরক্ষণ',
      cancel: 'বাতিল',
      faq: 'FAQ',
      terms: 'শর্তাবলী',
      privacy: 'গোপনীয়তা নীতি',
      subscriptions: 'সাবস্ক্রিপশন',
      shareApp: 'অ্যাপ শেয়ার করুন',
      deleteAccount: 'অ্যাকাউন্ট মুছুন',
      deleteAccountWarning: 'এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না',
      nameRequired: 'নাম প্রয়োজন',
      phoneInvalid: 'অবৈধ ফোন নম্বর',
      urlInvalid: 'অবৈধ URL',
      saveSuccess: 'প্রোফাইল সফলভাবে আপডেট হয়েছে',
      saveError: 'প্রোফাইল আপডেট করতে ব্যর্থ',
    },
    auth: {
      login: 'লগইন',
      signUp: 'সাইন আপ',
      email: 'ইমেইল',
      password: 'পাসওয়ার্ড',
      confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
      forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
      continueAsGuest: 'অতিথি হিসাবে চালিয়ে যান',
      dontHaveAccount: 'অ্যাকাউন্ট নেই?',
      alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      createAccount: 'অ্যাকাউন্ট তৈরি করুন',
      otpVerification: 'OTP যাচাইকরণ',
      otpSent: 'OTP আপনার ইমেইলে পাঠানো হয়েছে',
      enterOTP: 'OTP প্রবেশ করান',
      verify: 'যাচাই করুন',
      resendOTP: 'OTP আবার পাঠান',
      personalDetails: 'ব্যক্তিগত বিবরণ',
      uploadPhoto: 'ফটো আপলোড করুন',
      takePhoto: 'ফটো তুলুন',
      chooseFromGallery: 'গ্যালারি থেকে নির্বাচন করুন',
      continue: 'চালিয়ে যান',
      emailRequired: 'ইমেইল প্রয়োজন',
      emailInvalid: 'অবৈধ ইমেইল ফরম্যাট',
      passwordRequired: 'পাসওয়ার্ড প্রয়োজন',
      passwordMinLength: 'পাসওয়ার্ড কমপক্ষে 6 অক্ষরের হতে হবে',
      passwordMismatch: 'পাসওয়ার্ড মেলে না',
      otpRequired: 'OTP প্রয়োজন',
      otpInvalid: 'অবৈধ OTP',
      nameRequired: 'নাম প্রয়োজন',
      loginSuccess: 'লগইন সফল',
      loginError: 'লগইন ব্যর্থ',
      signUpSuccess: 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে',
      signUpError: 'সাইন আপ ব্যর্থ',
      otpSuccess: 'OTP সফলভাবে যাচাই করা হয়েছে',
      otpError: 'OTP যাচাইকরণ ব্যর্থ',
      resetPasswordDescription:
        'আপনার ইমেইল ঠিকানা লিখুন এবং আমরা আপনাকে পাসওয়ার্ড রিসেট করার জন্য একটি লিঙ্ক পাঠাব।',
      sendResetLink: 'রিসেট লিঙ্ক পাঠান',
      resetPasswordEmailSent: 'ইমেইল পাঠানো হয়েছে!',
      resetPasswordCheckEmail:
        'অনুগ্রহ করে পাসওয়ার্ড রিসেট নির্দেশাবলীর জন্য আপনার ইমেইল চেক করুন। লিঙ্কটি 1 ঘন্টার মধ্যে মেয়াদ শেষ হবে।',
      resetPasswordError: 'রিসেট ইমেইল পাঠাতে ব্যর্থ',
      rememberPassword: 'আপনার পাসওয়ার্ড মনে আছে?',
      backToLogin: 'লগইনে ফিরে যান',
    },
  },
  pa: {
    intro: {
      skip: 'ਛੱਡੋ',
      next: 'ਅਗਲਾ',
      getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
      welcome: 'SharePost ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
      subtitle: 'ਫੋਟੋ, ਥੀਮ ਅਤੇ ਹੋਰ ਬਹੁਤ ਕੁਝ ਨਾਲ ਸੁੰਦਰ ਪੋਸਟ ਬਣਾਓ',
    },
    common: {
      continue: 'ਜਾਰੀ ਰੱਖੋ',
      cancel: 'ਰੱਦ ਕਰੋ',
      save: 'ਸੇਵ ਕਰੋ',
      delete: 'ਮਿਟਾਓ',
      edit: 'ਸੰਪਾਦਨ ਕਰੋ',
      share: 'ਸਾਂਝਾ ਕਰੋ',
    },
    features: {
      addPhotos: 'ਆਪਣੀਆਂ ਫੋਟੋਆਂ ਜੋੜੋ',
      addPhotosDesc:
        'ਸੁੰਦਰ ਪਿਛੋਕੜਾਂ ਨਾਲ ਆਪਣੀਆਂ ਪਸੰਦੀਦਾ ਫੋਟੋਆਂ ਅਪਲੋਡ ਕਰੋ ਅਤੇ ਸਾਂਝਾ ਕਰੋ',
      personalize: 'ਆਪਣਾ ਪ੍ਰੋਫਾਈਲ ਨਿੱਜੀ ਬਣਾਓ',
      personalizeDesc: 'ਦੂਜਿਆਂ ਨਾਲ ਜੁੜਨ ਲਈ ਆਪਣਾ ਨਾਮ ਅਤੇ ਸੋਸ਼ਲ ਮੀਡੀਆ ਲਿੰਕ ਜੋੜੋ',
      celebrate: 'ਖਾਸ ਦਿਨ ਮਨਾਓ',
      celebrateDesc:
        'ਗਣਤੰਤਰ ਦਿਵਸ, ਤਿਉਹਾਰ ਅਤੇ ਪ੍ਰੇਰਣਾਦਾਇਕ ਵਿਚਾਰਾਂ ਵਰਗੇ ਥੀਮਾਂ ਵਿੱਚੋਂ ਚੁਣੋ',
      share: 'ਸਾਂਝਾ ਕਰੋ ਅਤੇ ਪ੍ਰੇਰਿਤ ਕਰੋ',
      shareDesc:
        'ਸੁੰਦਰ ਪੋਸਟ ਬਣਾਓ ਅਤੇ ਉਨ੍ਹਾਂ ਨੂੰ ਆਪਣੇ ਦੋਸਤਾਂ ਅਤੇ ਪਰਿਵਾਰ ਨਾਲ ਸਾਂਝਾ ਕਰੋ',
    },
    language: {
      title: 'ਭਾਸ਼ਾ ਚੁਣੋ',
      subtitle: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ',
      selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
      currentLanguage: 'ਮੌਜੂਦਾ ਭਾਸ਼ਾ',
      continue: 'ਜਾਰੀ ਰੱਖੋ',
    },
    home: {
      title: 'ਹੋਮ',
      welcome: 'ਸਵਾਗਤ',
      welcomeUser: 'ਸਵਾਗਤ ਯੂਜ਼ਰ',
      goodMorning: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
      goodAfternoon: 'ਨਮਸਕਾਰ',
      goodEvening: 'ਸ਼ੁਭ ਸੰਧਿਆ',
      searchPlaceholder: 'ਖੋਜੋ...',
      selectCategory: 'ਸ਼੍ਰੇਣੀ ਚੁਣੋ',
      createPost: 'ਪੋਸਟ ਬਣਾਓ',
      myPosts: 'ਮੇਰੀਆਂ ਪੋਸਟਾਂ',
      noPosts: 'ਅਜੇ ਤੱਕ ਕੋਈ ਪੋਸਟ ਨਹੀਂ',
      createFirstPost: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਪਹਿਲੀ ਪੋਸਟ ਬਣਾਓ',
      categories: {
        all: 'ਸਭ',
        newYear: 'ਨਵਾਂ ਸਾਲ',
        goodMorning: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
        goodNight: 'ਸ਼ੁਭ ਰਾਤ',
        suvichar: 'ਸੁਵਿਚਾਰ',
      },
      download: 'ਡਾਉਨਲੋਡ',
      edit: 'ਸੰਪਾਦਨ ਕਰੋ',
      more: 'ਹੋਰ',
      customize: 'ਕਸਟਮਾਈਜ਼ ਕਰੋ',
    },
    settings: {
      title: 'ਸੈਟਿੰਗਾਂ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      language: 'ਭਾਸ਼ਾ',
      theme: 'ਥੀਮ',
      darkMode: 'ਡਾਰਕ ਮੋਡ',
      lightMode: 'ਲਾਈਟ ਮੋਡ',
      about: 'ਬਾਰੇ',
      logout: 'ਲਾਗਆਉਟ',
      version: 'ਵਰਜ਼ਨ',
    },
    profile: {
      title: 'ਪ੍ਰੋਫਾਈਲ',
      editProfile: 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਨ ਕਰੋ',
      fullName: 'ਪੂਰਾ ਨਾਮ',
      phoneNumber: 'ਫੋਨ ਨੰਬਰ',
      bio: 'ਬਾਇਓ / ਵਰਣਨ',
      facebook: 'ਫੇਸਬੁਕ',
      instagram: 'ਇੰਸਟਾਗ੍ਰਾਮ',
      twitter: 'ਟਵਿਟਰ',
      save: 'ਸੇਵ ਕਰੋ',
      cancel: 'ਰੱਦ ਕਰੋ',
      faq: 'FAQ',
      terms: 'ਸ਼ਰਤਾਂ ਅਤੇ ਨਿਯਮ',
      privacy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
      subscriptions: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ',
      shareApp: 'ਐਪ ਸਾਂਝਾ ਕਰੋ',
      deleteAccount: 'ਖਾਤਾ ਮਿਟਾਓ',
      deleteAccountWarning: 'ਇਸ ਕਾਰਵਾਈ ਨੂੰ ਪੂਰਵਵਰਤੀ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ',
      nameRequired: 'ਨਾਮ ਲੋੜੀਂਦਾ ਹੈ',
      phoneInvalid: 'ਅਵੈਧ ਫੋਨ ਨੰਬਰ',
      urlInvalid: 'ਅਵੈਧ URL',
      saveSuccess: 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅਪਡੇਟ ਕੀਤਾ ਗਿਆ',
      saveError: 'ਪ੍ਰੋਫਾਈਲ ਅਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ',
    },
    auth: {
      login: 'ਲਾਗਇਨ',
      signUp: 'ਸਾਇਨ ਅਪ',
      email: 'ਈਮੇਲ',
      password: 'ਪਾਸਵਰਡ',
      confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
      forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
      continueAsGuest: 'ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
      dontHaveAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
      alreadyHaveAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
      createAccount: 'ਖਾਤਾ ਬਣਾਓ',
      otpVerification: 'OTP ਪੜਤਾਲ',
      otpSent: 'OTP ਤੁਹਾਡੇ ਈਮੇਲ ਤੇ ਭੇਜਿਆ ਗਿਆ ਹੈ',
      enterOTP: 'OTP ਦਾਖਲ ਕਰੋ',
      verify: 'ਪੜਤਾਲ ਕਰੋ',
      resendOTP: 'OTP ਦੁਬਾਰਾ ਭੇਜੋ',
      personalDetails: 'ਵਿਅਕਤੀਗਤ ਵਿਵਰਣ',
      uploadPhoto: 'ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
      takePhoto: 'ਫੋਟੋ ਲਓ',
      chooseFromGallery: 'ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ',
      continue: 'ਜਾਰੀ ਰੱਖੋ',
      emailRequired: 'ਈਮੇਲ ਲੋੜੀਂਦਾ ਹੈ',
      emailInvalid: 'ਅਵੈਧ ਈਮੇਲ ਫਾਰਮੈਟ',
      passwordRequired: 'ਪਾਸਵਰਡ ਲੋੜੀਂਦਾ ਹੈ',
      passwordMinLength: 'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ',
      passwordMismatch: 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
      otpRequired: 'OTP ਲੋੜੀਂਦਾ ਹੈ',
      otpInvalid: 'ਅਵੈਧ OTP',
      nameRequired: 'ਨਾਮ ਲੋੜੀਂਦਾ ਹੈ',
      loginSuccess: 'ਲਾਗਇਨ ਸਫਲ',
      loginError: 'ਲਾਗਇਨ ਅਸਫਲ',
      signUpSuccess: 'ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਬਣਾਇਆ ਗਿਆ',
      signUpError: 'ਸਾਇਨ ਅਪ ਅਸਫਲ',
      otpSuccess: 'OTP ਸਫਲਤਾਪੂਰਵਕ ਪੜਤਾਲ ਕੀਤਾ ਗਿਆ',
      otpError: 'OTP ਪੜਤਾਲ ਅਸਫਲ',
      resetPasswordDescription:
        'ਆਪਣਾ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ ਅਤੇ ਅਸੀਂ ਤੁਹਾਨੂੰ ਆਪਣਾ ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰਨ ਲਈ ਇੱਕ ਲਿੰਕ ਭੇਜਾਂਗੇ।',
      sendResetLink: 'ਰੀਸੈਟ ਲਿੰਕ ਭੇਜੋ',
      resetPasswordEmailSent: 'ਈਮੇਲ ਭੇਜਿਆ ਗਿਆ!',
      resetPasswordCheckEmail:
        'ਕਿਰਪਾ ਕਰਕੇ ਪਾਸਵਰਡ ਰੀਸੈਟ ਨਿਰਦੇਸ਼ਾਂ ਲਈ ਆਪਣਾ ਈਮੇਲ ਜਾਂਚੋ। ਲਿੰਕ 1 ਘੰਟੇ ਵਿੱਚ ਮਿਆਦ ਪੁੱਗ ਜਾਵੇਗੀ।',
      resetPasswordError: 'ਰੀਸੈਟ ਈਮੇਲ ਭੇਜਣ ਵਿੱਚ ਅਸਫਲ',
      rememberPassword: 'ਆਪਣਾ ਪਾਸਵਰਡ ਯਾਦ ਹੈ?',
      backToLogin: 'ਲੌਗਇਨ ਤੇ ਵਾਪਸ ਜਾਓ',
    },
  },
};

export default strings.en;
